### ISSUE TITLE
More compact libcef.so?

### ISSUE THREAD

**Issue by ryanerwin** [Gurkengewuerz/cefgo#2]
I was looking through the release directory and it looks like the `libcef.so` that I downloaded is 1012 MB.... I'm surprised it's so big!

Is there a more compact version of this library?

**Comment by Gurkengewuerz** [comment]
Not not really. As i said in go-ultralight the Chrome Embedded Framework is much larger than everything else just because you pack a complete Chromium Engine inside your project.

**Comment by ryanerwin** [comment]
That's strange. I assumed that Electron was also using a complete chromium + complete nodejs and would therefore assume it would be even much larger than CEF which only includes a standalone Chrome.

For reference, the actual electron binary is 122MB, and the related shared objects are less than 30MB.

```
-rwxr-xr-x 1 ryan ryan   7M Aug 13 13:14 chrome-sandbox
-rw-r--r-- 1 ryan ryan   1M Aug 13 13:14 chrome_100_percent.pak
-rw-r--r-- 1 ryan ryan   1M Aug 13 13:14 chrome_200_percent.pak
-rwxr-xr-x 1 ryan ryan 122M Aug 13 13:14 electron
-rw-r--r-- 1 ryan ryan  11M Aug 13 13:14 icudtl.dat
-rwxr-xr-x 1 ryan ryan   1M Aug 13 13:14 libEGL.so
-rwxr-xr-x 1 ryan ryan   9M Aug 13 13:14 libGLESv2.so
-rwxr-xr-x 1 ryan ryan   3M Aug 13 13:14 libffmpeg.so
-rwxr-xr-x 1 ryan ryan   5M Aug 13 13:14 libvk_swiftshader.so
-rwxr-xr-x 1 ryan ryan   9M Aug 13 13:14 libvulkan.so
-rw-r--r-- 1 ryan ryan   5M Aug 13 13:14 resources.pak
-rw-r--r-- 1 ryan ryan   1M Aug 13 13:14 snapshot_blob.bin
-rw-r--r-- 1 ryan ryan   1M Aug 13 13:14 v8_context_snapshot.bin
-rw-r--r-- 1 ryan ryan   1M Aug 13 13:14 version
-rw-r--r-- 1 ryan ryan   1M Aug 13 13:14 vk_swiftshader_icd.json
```

**Comment by Gurkengewuerz** [comment]
@ryanerwin you can see in the [cef wiki](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage.md#markdown-header-windows) all needed shared objects. And yes, `libcef.so` is one of them. Keep in mind electron isn't using the Chromium Embedded Framework.
